# Generated by Django 4.1.5 on 2023-01-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="weight",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="reps",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="sets",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
