# Generated by Django 4.1.5 on 2023-01-25 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
        ("exercises", "0002_exercise_weight_alter_exercise_reps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="workout",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises",
                to="tracker.workout",
            ),
        ),
    ]
