# Generated by Django 4.1.5 on 2023-01-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0003_exercise_workout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="goal",
            field=models.CharField(default=0, max_length=200),
        ),
    ]
